# Generated by Django 3.1.4 on 2020-12-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post_tag', to='posts.Tag'),
        ),
    ]
