# Generated by Django 3.1.3 on 2020-11-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_like'),
        ('posts', '0005_auto_20201128_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='comments.comment'),
        ),
    ]
