# Generated by Django 3.1.3 on 2020-11-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
