# Generated by Django 3.1.3 on 2020-11-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201127_2017'),
        ('likes', '0001_initial'),
        ('users', '0002_auto_20201120_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='likes.like'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='posts.post'),
        ),
    ]
