# Generated by Django 3.1.3 on 2020-11-29 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('web', '웹'), ('kakao', '카카오'), ('google', '구글')], default='web', max_length=50, verbose_name='로그인 방법'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='팔로워'),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='팔로잉'),
        ),
    ]
