# Generated by Django 3.1.3 on 2020-11-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201127_2017'),
        ('comments', '0001_initial'),
        ('likes', '0001_initial'),
        ('users', '0003_auto_20201127_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='comments.comment', verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='likes.like', verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='posts.post', verbose_name='포스트'),
        ),
    ]
