# Generated by Django 3.1.3 on 2020-11-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201128_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_post',
        ),
    ]
