# Generated by Django 3.1.3 on 2020-12-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_relation', '0002_auto_20201204_0107'),
        ('users', '0006_auto_20201203_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followees',
            field=models.ManyToManyField(blank=True, related_name='user', to='follow_relation.FollowRelation', verbose_name='팔로워'),
        ),
    ]
