# Generated by Django 3.1.4 on 2020-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20201211_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
