# Generated by Django 3.1.3 on 2020-12-07 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('follow_relation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followrelation',
            name='followee',
            field=models.ManyToManyField(blank=True, related_name='followee', to=settings.AUTH_USER_MODEL, verbose_name='팔로워'),
        ),
        migrations.AddField(
            model_name='followrelation',
            name='follower',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
