# Generated by Django 3.1.3 on 2020-12-03 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('follow_relation', '0002_auto_20201204_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelation',
            name='followee',
            field=models.ManyToManyField(blank=True, null=True, related_name='followee', to=settings.AUTH_USER_MODEL, verbose_name='팔로워'),
        ),
    ]
